### ISSUE TITLE
[Client] CreatePage 기능 구현

### ISSUE THREAD

**Issue by holystorySeo** [codestates/BookDam#83]
### ISSUE
- Group:  `client`, `server`, `sr`
- Type: `bug`, `feature`, `delete`
- Detail: fix actions from client redux

### TODO
1. [x] CreatePage 기본 뼈대 구현
2. [x] 책 검색 결과 모달 창 구현
3. [x] 입력 콘텐츠 post 요청

### Estimated time
> Pick one
### Labels
- Estimated time: `E: 3h`
- Group : `client`
- Urgency: `High`
